<?php

namespace webd\language;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-12-15 at 17:21:01.
 */
class LCSTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var LCS
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new LCS("BACBAD", "BATBAD");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers webd\language\LCS::LCS
     * @todo   Implement testLCS().
     */
    public function testValue() {
        $this->assertEquals($this->object->value(), "BABAD");
    }

    /**
     * @covers webd\language\LCS::length
     * @todo   Implement testLength().
     */
    public function testLength() {
        $this->assertEquals($this->object->length(), 5);
    }
    
    public function testDistance() {
        $this->assertEquals($this->object->distance(), 2);
    }

    /**
     * @covers webd\language\LCS::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
    }

}
