<?php

namespace webd\language;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-13 at 08:50:24.
 */
class PorterStemmerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var PorterStemmer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PorterStemmer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers webd\language\PorterStemmer::Stem
     * @todo   Implement testStem().
     */
    public function testStem() {
        $this->assertEquals(PorterStemmer::Stem("caresses"), "caress");
    }

}
