<?php

namespace webd\language;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-13 at 09:21:57.
 */
class StringDistanceTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Distance
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new StringDistance;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers webd\language\Distance::Jaro
     * @todo   Implement testJaro().
     */
    public function testJaro() {
        $this->assertEquals(0.944, StringDistance::Jaro("MARTHA", "MARHTA"), "", 0.001);
    }

    /**
     * @covers webd\language\Distance::JaroWinkler
     * @todo   Implement testJaroWinkler().
     */
    public function testJaroWinkler() {
        $this->assertEquals(0.961, StringDistance::JaroWinkler("MARTHA", "MARHTA", 0.1), "", 0.001);
    }
    
    public function testLevenshtein() {
        $this->assertEquals(6, StringDistance::Levenshtein("bordure", "contexte"));
    }

}
